-- 数据库迁移脚本：表结构变更一律新增 V{版本}__{说明}.sql，
-- 已经执行过的脚本不要修改（Flyway 会校验 checksum）。
-- 写法保持标准 SQL：H2（本地）与 PostgreSQL（生产）都能执行。
CREATE TABLE IF NOT EXISTS users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone      VARCHAR(32) NOT NULL UNIQUE,
    nickname   VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
